### ISSUE TITLE
Getting this error when restoring from S3.

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [ysde/grafana-backup-tool#91] opened 2020-09-16 18:10 UTC

**Comment by ysde** [comment] 2020-09-21 04:24
Hi @rmccarthy-ellevation 

Can you provide some descriptions?

Thank you

**Comment by acjohnson** [comment] 2020-09-21 05:26
I'm pretty sure this is a duplicate of #92

**Comment by tommyjcarpenter** [comment] 2021-05-26 12:14
I am also having this issue still; I replied to #92 which was closed but not sure about the closure: https://github.com/ysde/grafana-backup-tool/issues/92

**Closed** 2021-05-26 13:04 UTC

**Comment by acjohnson** [comment] 2021-05-26 14:44
@tommyjcarpenter if this is the error you are getting then it means that the value of `s3_bucket_key"` in your `~/.grafana-backup.json` doesn't exist within the actual s3 bucket you are trying to restore from. They call it a "key" but it's just a folder inside of the s3 bucket that you backup/restore to/from. 
```
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

**Comment by tommyjcarpenter** [comment] 2021-05-26 14:59
@acjohnson it *does* exist though, since backups work! Does the JSON need a trailing slash for downloads but not uploads?
