### ISSUE TITLE
Folder not found error on restore.

### ISSUE THREAD

**Issue by gurpalw** [ysde/grafana-backup-tool#111] opened 2020-12-05 17:06 UTC
I took a backup from a grafana server using the command below.

`grafana-backup save --components dashboards,datasources,folders`

I have my .envrc set up, and the save works successfully with no errors in the log.

I've then installed a fresh instance of grafana and i'm trying to restore but i get the below errors.

please advise.

I am using grafana 7.3.3.

```
grafana health: https://grafana-restore-test.xxx.xxxx.net.cn/api/health
[DEBUG] resp status: 200
[DEBUG] resp body: {u'commit': u'2489dc4d3a', u'version': u'7.3.3', u'database': u'ok'}
grafana auth check: https://grafana-restore-test.xx.xx.net.cn/api/auth/keys
[DEBUG] resp status: 200
[DEBUG] resp body: [{u'role': u'Admin', u'id': 1, u'name': u'restoretest'}]

########################################

restoring dashboards: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmphhqOuu/_OUTPUT_/dashboards/202012041839/9diCMklZz.dashboard
[DEBUG] resp status: 200
[DEBUG] resp body: {u'status': u'success', u'uid': u'9diCMklZz', u'url': u'/d/9diCMklZz/elasticsearch-mgmt', u'slug': u'elasticsearch-mgmt', u'version': 1, u'id': 29}
create dashboard ElasticSearch - MGMT response status: 200, msg: {u'status': u'success', u'uid': u'9diCMklZz', u'url': u'/d/9diCMklZz/elasticsearch-mgmt', u'slug': u'elasticsearch-mgmt', u'version': 1, u'id': 29}

restoring dashboards: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmphhqOuu/_OUTPUT_/dashboards/202012041839/ZGtkv2-Zz.dashboard
[DEBUG] resp status: 404
[DEBUG] resp body: {u'status': u'not-found', u'message': u'Folder not found'}
query folder:IjBCShaZz, status:404
Traceback (most recent call last):
  File "/usr/local/bin/grafana-backup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/cli.py", line 46, in main
    restore(args, settings)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/restore.py", line 60, in main
    restore_components(args, settings, restore_functions, tmpdir)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/restore.py", line 85, in restore_components
    restore_functions[ext[:-1]](args, settings, file_path)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/create_dashboard.py", line 20, in main
    'folderId': get_folder_id_from_old_folder_url(content['meta']['folderUrl'], grafana_url, http_post_headers, verify_ssl, client_cert, debug),
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/dashboardApi.py", line 85, in get_folder_id_from_old_folder_url
    return folder_data['id']
KeyError: 'id'
```

When i check the UI, i can see that a small number of dashboards have been restored, but the vast majority have not.
My .envrc is below for info purposes.

export GRAFANA_URL=https://grafana-restore-test.xxxx.xxxx.net.cn
export GRAFANA_TOKEN=xxxxx=
export GRAFANA_ADMIN_ACCOUNT=xxxx
export GRAFANA_ADMIN_PASSWORD=xxx

**Comment by acjohnson** [comment] 2020-12-06 16:08
Just curious what happens when you restore the folders first and then the dashboards manually @gurpalw 
```grafana-backup restore <archive_file> --components=folders```

I suspect the problem is we are using an unordered dictionary in restore.py
```
 44     restore_functions = { 'folder': create_folder,
 45                           'datasource': create_datasource,
 46                           'dashboard': create_dashboard,
 47                           'alert_channel': create_alert_channel,
 48                           'organization': create_org,
 49                           'user': create_user}

```

**Comment by gurpalw** [comment] 2020-12-06 19:10
I restored the folders successfully, using your command. I then tried to restore the dashboards using: `grafana-backup restore --components dashboards _OUTPUT_/202012041839.tar.gz`


but i received the below error.

```grafana health: https://grafana-restore-test.xx.xx.net.cn/api/health
[DEBUG] resp status: 200
[DEBUG] resp body: {u'commit': u'2489dc4d3a', u'version': u'7.3.3', u'database': u'ok'}
grafana auth check: https://grafana-restore-test.xx.xxx.net.cn/api/auth/keys
[DEBUG] resp status: 200
[DEBUG] resp body: [{u'role': u'Admin', u'id': 1, u'name': u'restoretest'}]

########################################

restoring dashboards: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmp250hwY/_OUTPUT_/dashboards/202012041839/9diCMklZz.dashboard
[DEBUG] resp status: 200
[DEBUG] resp body: {u'status': u'success', u'uid': u'9diCMklZz', u'url': u'/d/9diCMklZz/elasticsearch-mgmt', u'slug': u'elasticsearch-mgmt', u'version': 2, u'id': 29}
create dashboard ElasticSearch - MGMT response status: 200, msg: {u'status': u'success', u'uid': u'9diCMklZz', u'url': u'/d/9diCMklZz/elasticsearch-mgmt', u'slug': u'elasticsearch-mgmt', u'version': 2, u'id': 29}

restoring dashboards: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmp250hwY/_OUTPUT_/dashboards/202012041839/ZGtkv2-Zz.dashboard
[DEBUG] resp status: 404
[DEBUG] resp body: {u'status': u'not-found', u'message': u'Folder not found'}
query folder:IjBCShaZz, status:404
Traceback (most recent call last):
  File "/usr/local/bin/grafana-backup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/cli.py", line 46, in main
    restore(args, settings)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/restore.py", line 60, in main
    restore_components(args, settings, restore_functions, tmpdir)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/restore.py", line 85, in restore_components
    restore_functions[ext[:-1]](args, settings, file_path)
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/create_dashboard.py", line 20, in main
    'folderId': get_folder_id_from_old_folder_url(content['meta']['folderUrl'], grafana_url, http_post_headers, verify_ssl, client_cert, debug),
  File "/usr/local/lib/python2.7/site-packages/grafana_backup/dashboardApi.py", line 85, in get_folder_id_from_old_folder_url
    return folder_data['id']
KeyError: 'id'
```

**Comment by acjohnson** [comment] 2020-12-06 19:29
It is failing to restore to a folder with ID `IjBCShaZz` which apparently does not exist. If the folder was restored properly you should be able to browse to `http://<grafana_ip>:<grafana_port>/dashboards/f/IjBCShaZz`

Most likely it will return a "Folder not found" error because that folder does not appear to exist based on the command output you provided.

Does the folder `restore` show errors when you run it?

I've tested the folder restore and dashboard restore with nested dashboards and I do not experience this error.

**Comment by gurpalw** [comment] 2020-12-06 20:38
I have just deleted all folders via the UI. 

Then i ran the restore folders command again. `grafana-backup restore --components folders _OUTPUT_/202012041839.tar.gz`

```
grafana health: https://grafana-restore-test.xxx.xx.net.cn/api/health
[DEBUG] resp status: 200
[DEBUG] resp body: {u'commit': u'2489dc4d3a', u'version': u'7.3.3', u'database': u'ok'}
grafana auth check: https://grafana-restore-test.xxx.xxx.net.cn/api/auth/keys
[DEBUG] resp status: 200
[DEBUG] resp body: [{u'role': u'Admin', u'id': 1, u'name': u'restoretest'}]

########################################

restoring folders: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmpdP3TDz/_OUTPUT_/folders/202012041839/b9unwd8Zz.folder
[DEBUG] resp status: 200
[DEBUG] resp body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:48Z', u'uid': u'b9unwd8Zz', u'title': u'Kubernetes', u'url': u'/dashboards/f/b9unwd8Zz/kubernetes', u'created': u'2020-12-06T20:32:48Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 48}
**create folder Kubernetes, status: 200, msg: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:48Z', u'uid': u'b9unwd8Zz', u'title': u'Kubernetes', u'url': u'/dashboards/f/b9unwd8Zz/kubernetes', u'created': u'2020-12-06T20:32:48Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 48}
restoring folders: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmpdP3TDz/_OUTPUT_/folders/202012041839/IjBCShaZz.folder
[DEBUG] resp status: 400
[DEBUG] resp body: {u'message': u'A folder or dashboard in the general folder with the same name already exists'}
create folder SRE, status: 400, msg: {u'message': u'A folder or dashboard in the general folder with the same name already exists'}**
restoring folders: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmpdP3TDz/_OUTPUT_/folders/202012041839/jw0Uh2nMz.folder
[DEBUG] resp status: 200
[DEBUG] resp body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:52Z', u'uid': u'jw0Uh2nMz', u'title': u'Data Engineering', u'url': u'/dashboards/f/jw0Uh2nMz/data-engineering', u'created': u'2020-12-06T20:32:52Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 49}
create folder Data Engineering, status: 200, msg: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:52Z', u'uid': u'jw0Uh2nMz', u'title': u'Data Engineering', u'url': u'/dashboards/f/jw0Uh2nMz/data-engineering', u'created': u'2020-12-06T20:32:52Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 49}
restoring folders: /var/folders/f3/jzqmh4753hl9yzgvmrdrw55h0000gq/T/tmpdP3TDz/_OUTPUT_/folders/202012041839/gIb7kCTMz.folder
[DEBUG] resp status: 200
[DEBUG] resp body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:54Z', u'uid': u'gIb7kCTMz', u'title': xxxx Central', u'url': u'/dashboards/f/gIb7kCTMz/xxxx-central', u'created': u'2020-12-06T20:32:54Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 50}
create folder xxx Central, status: 200, msg: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2020-12-06T20:32:54Z', u'uid': u'gIb7kCTMz', u'title': u'Vxxx Central', u'url': u'/dashboards/f/gIb7kCTMz/xxxx-central', u'created': u'2020-12-06T20:32:54Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 50}
```

It says one of the folders already exists, even though i made sure to delete all folders via the UI.

**Comment by acjohnson** [comment] 2020-12-06 21:33
It seems like you've got something strange going on with a folder (different one this time btw) It appears to be named `SRE`. Have you tried browsing to `https://grafana-restore-test.xxx.xx.net.cn/dashboards/f/jw0Uh2nMz` yet?

**Comment by gurpalw** [comment] 2020-12-07 11:32
Yes, i can reach that page fine, and see an empty folder titled "Data Engineering".

**Comment by gurpalw** [comment] 2020-12-07 14:32
Ok, i figured out the issue with a duplicate dashboard was my fault.

But the initial issue with the folder not found error, still occurs. It resolves if i restore folders first, then dashboards afterwards.

**Comment by acjohnson** [comment] 2020-12-07 19:14
Awesome thanks for confirming once #112 is merged this should be resolved.

**Comment by acjohnson** [comment] 2020-12-17 01:46
@ysde this issue is resolved and can be closed

**Comment by ysde** [comment] 2020-12-22 15:53
Thanks @acjohnson and @gurpalw

**Closed by ysde** 2020-12-22 15:53 UTC
